version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./../stack/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySqLR00TPassworD
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
    networks:
      - stack
  web:
    image: magento/magento-cloud-docker-nginx
    networks:
      - stack
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../pub/index.php:/app/pub/index.php:ro
  fpm:
    image: meanbee/magento2-php:7.2-fpm
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - stack
    volumes:
      - ./../:/app

  appdata:
    image: tianon/true
    volumes:
      - ./../:/var/www/magento
  
  cli:
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.2-cli
    links:
      - db
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./../php.env
      - ./../composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento.test/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.3.*

networks:
  stack:
    external: false
  proxy:
    external: true

  